# Generated by Django 2.0.5 on 2018-06-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('files_app', '0001_initial'), ('files_app', '0002_auto_20180525_2153'), ('files_app', '0003_auto_20180525_2253'), ('files_app', '0004_auto_20180526_1106'), ('files_app', '0005_auto_20180526_1127'), ('files_app', '0006_objectwithfile_file_name'), ('files_app', '0007_auto_20180528_0656')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectWithFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('status', models.CharField(choices=[('new', 'new'), ('processed', 'processed')], default='new', max_length=15)),
                ('file_name', models.CharField(blank=True, default='', max_length=249)),
            ],
        ),
    ]
