version: "3"

services:

  nginx:
    image: nginx:latest
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
     - /log
     - static:/static
     - media:/media
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
    links:
      - django
    depends_on:
      - django
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


  django:
    hostname: "django"
    build: .
    image: "django_celery_example"
    restart: "always"
    entrypoint: /entrypoints/webserver.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
      - /log
      - static:/static
      - media:/media
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  celery_worker:
    image: "django_celery_example"
    restart: "always"
    entrypoint: /entrypoints/celeryworker.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
      - /log
    links:
      - db
      - redis
      - django
    depends_on:
      - django

  celery_beat:
    image: "django_celery_example"
    restart: "always"
    entrypoint: /entrypoints/celerybeat.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
      - /log
    links:
      - db
      - redis
      - django
    depends_on:
      - django

  celery_flower:
    image: "django_celery_example"
    restart: "always"
    entrypoint: /entrypoints/celeryflower.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
      - /log
    links:
      - redis
      - django
      - celery_worker
      - celery_beat
    depends_on:
      - django
      - celery_beat
      - celery_worker
    ports:
      - 5555:5555

  db:
    hostname: "db"
    image: "postgres:9.6"
    env_file:
      - django_env_file
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    hostname: "redis"
    image: "redis"
    volumes:
      - redis_data:/data
    depends_on:
      - db

volumes:
  db_data:
  redis_data:
  nginx_log:
  static:
  media: