version: "3"

services:

  nginx:
    image: nginx
    hostname: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./upload:/media/upload:ro
      - nginx_log:/var/log/nginx
    command: [nginx, '-g', 'daemon off;']
    links:
      - django
    depends_on:
      - django
    ports:
      - 80:80

  django:
    hostname: "django"
    image: "test:test"
    restart: "always"
    entrypoint: /entrypoints/webserver.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
      - ./upload:/media/upload
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  celery_worker:
    image: "test:test"
    restart: "always"
    entrypoint: /entrypoints/celeryworker.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
    links:
      - db
      - redis
    depends_on:
      - django

  celery_beat:
    image: "test:test"
    restart: "always"
    entrypoint: /entrypoints/celerybeat.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
    links:
      - db
      - redis
    depends_on:
      - django

  celery_flower:
    image: "test:test"
    restart: "always"
    entrypoint: /entrypoints/celeryflower.sh
    env_file:
      - django_env_file
    volumes:
      - ./src:/app
      - ./entrypoints:/entrypoints
    links:
      - redis
      - celery_worker
      - celery_beat
    depends_on:
      - django
      - celery_beat
      - celery_worker
    ports:
      - 5555:5555

  db:
    hostname: "db"
    image: "postgres:9.6"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    hostname: "redis"
    image: "redis"
    volumes:
      - redis_data:/data
    depends_on:
      - db

volumes:
  db_data:
  redis_data:
  nginx_log: