# Generated by Django 2.0.5 on 2018-06-18 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SomeFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_time', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('status', models.CharField(choices=[('new', 'new'), ('progress', 'progress'), ('done', 'done')], default='new', max_length=20)),
                ('file_name', models.CharField(blank=True, default='', editable=False, max_length=249)),
            ],
        ),
        migrations.AddField(
            model_name='filecontent',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_application.SomeFile'),
        ),
    ]
